 console.log("Boa Tarde Turma 110!")
 console.log("Estou no senac Largo 13")
 console.log("Boa Tarde Turma 110!")
 console.log("Boa Tarde Turma 110!")
 console.log("Boa Tarde Turma 110!")
 console.log("Boa Tarde Turma 110!")